[toolchain]
anchor_version = "0.31.1"
solana_version = "1.18.14"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_oapp = "CcGjSmj2ivNWcd6Q1J8Sew7fLPXNkvGQnXgKSgo5wFxz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
